"""Generate a committed Lua palette lookup from a TexturePacker-style atlas.

Example:
    python3 _3_atlas_palette.py atlas.png atlas.json palettes.lua --colors 5 --blocks 4
"""

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image


# ----------------------------
# HELPERS
# ----------------------------
def _args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description="Generate per-sprite Lua palettes from a PNG/JSON atlas.")
	parser.add_argument("atlas_png", type=Path)
	parser.add_argument("atlas_json", type=Path)
	parser.add_argument("output_lua", type=Path)
	parser.add_argument("--colors", type=int, default=5, choices=range(3, 6))
	parser.add_argument("--blocks", type=int, default=4)
	parser.add_argument("--samples-per-block", type=int, default=2048)
	parser.add_argument("--alpha-threshold", type=int, default=24)
	parser.add_argument("--min-luma", type=float, default=45)
	parser.add_argument("--max-luma", type=float, default=248)
	parser.add_argument("--white-luma", type=float, default=218)
	parser.add_argument("--white-chroma", type=float, default=18)
	parser.add_argument("--min-distance", type=float, default=28)
	return parser.parse_args()


def _frame_rect(entry: dict) -> tuple[int, int, int, int]:
	frame = entry.get("frame", entry)
	return frame["x"], frame["y"], frame["w"], frame["h"]


def _valid_rgb(block: np.ndarray, args: argparse.Namespace) -> np.ndarray:
	pixels = block.reshape(-1, 4)
	rgb = pixels[:, :3].astype(np.float32)
	alpha = pixels[:, 3]
	luma = 0.2126*rgb[:, 0] + 0.7152*rgb[:, 1] + 0.0722*rgb[:, 2]
	chroma = rgb.max(axis=1) - rgb.min(axis=1)
	mask = (alpha >= args.alpha_threshold) & (luma >= args.min_luma) & (luma <= args.max_luma)
	mask &= ~((luma >= args.white_luma) & (chroma <= args.white_chroma))
	return pixels[mask, :3]


def _block_samples(sprite: Image.Image, args: argparse.Namespace) -> np.ndarray:
	rgba = np.asarray(sprite.convert("RGBA"))
	h, w = rgba.shape[:2]
	samples = []
	for by in range(args.blocks):
		for bx in range(args.blocks):
			x0, x1 = bx*w//args.blocks, (bx + 1)*w//args.blocks
			y0, y1 = by*h//args.blocks, (by + 1)*h//args.blocks
			pixels = _valid_rgb(rgba[y0:y1, x0:x1], args)
			if len(pixels) > args.samples_per_block:
				indices = np.linspace(0, len(pixels) - 1, args.samples_per_block, dtype=np.int64)
				pixels = pixels[indices]
			if len(pixels):
				samples.append(pixels)
	if not samples:
		raise RuntimeError("Sprite contains no pixels after palette filtering")
	return np.concatenate(samples).astype(np.uint8)


def _color_distance(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
	return float(np.linalg.norm(np.asarray(a, dtype=np.float32) - np.asarray(b, dtype=np.float32)))


def _quantized_palette(samples: np.ndarray, count: int, min_distance: float) -> list[tuple[int, int, int]]:
	strip = Image.fromarray(samples.reshape(1, -1, 3), "RGB")
	quantized = strip.quantize(colors=min(256, count*3), method=Image.Quantize.MEDIANCUT)
	palette = quantized.getpalette()
	candidates = [tuple(palette[3*idx:3*idx + 3]) for _, idx in sorted(quantized.getcolors() or [], reverse=True)]
	colors = []
	for color in candidates:
		if all(_color_distance(color, used) >= min_distance for used in colors):
			colors.append(color)
	if len(colors) < 3:
		for color in candidates:
			if color not in colors:
				colors.append(color)
			if len(colors) >= 3:
				break
	return colors[:count]


def _lua_color(color: tuple[int, int, int]) -> str:
	return f'hex("#{color[0]:02X}{color[1]:02X}{color[2]:02X}FF")'


def _lua_table(palettes: dict[str, list[tuple[int, int, int]]], source: str) -> str:
	lines = [f'-- Generated by _3_atlas_palette.py from {source}.', 'local hex = require("HMfns.animate.color.color_utils").hex_to_rgba', "", "return {"]
	for key, colors in palettes.items():
		lines.append(f'    ["{key}"] = {{ ' + ", ".join(_lua_color(color) for color in colors) + " },")
	lines.append("}")
	return "\n".join(lines) + "\n"


# ----------------------------
# MAIN
# ----------------------------
def main() -> None:
	args = _args()
	if args.blocks < 1 or args.samples_per_block < 1:
		raise ValueError("--blocks and --samples-per-block must be positive")

	with args.atlas_json.open("r", encoding="utf-8") as file:
		data = json.load(file)
	frames = data.get("frames", data)

	palettes = {}
	with Image.open(args.atlas_png) as atlas:
		atlas = atlas.convert("RGBA")
		for key in sorted(frames):
			x, y, w, h = _frame_rect(frames[key])
			sprite = atlas.crop((x, y, x + w, y + h))
			palettes[key] = _quantized_palette(_block_samples(sprite, args), args.colors, args.min_distance)

	args.output_lua.parent.mkdir(parents=True, exist_ok=True)
	args.output_lua.write_text(_lua_table(palettes, args.atlas_png.name), encoding="utf-8")
	print(f"Wrote {len(palettes)} palettes to {args.output_lua}")


if __name__ == "__main__":
	main()
